import axios from "axios";
import type {
  GetServerSideProps,
  InferGetServerSidePropsType,
  NextPage,
} from "next";
import Head from "next/head";
import Image from "next/image";
import { stringify } from "querystring";
import { Suspense } from "react";
import styles from "../styles/Home.module.css";
import {
  getIPAddress,
  getTimeZone,
  getTimeZoneOffset,
} from "./api/geolocation";
import Clock from "./components/clock";
import { timezones } from "./lib/timezones";

type Props = {
  ip: string;
  timezone: string;
  offset: number;
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const ip = await getIPAddress();
  const timezone = await getTimeZone();
  const offset = await getTimeZoneOffset();
  // const offset = parseInt(offset_str, 10);

  // console.log(offset)
  // console.log(ip, timezone);
  // console.log(timezones);
  return {
    props: { ip, timezone, offset }, // will be passed to the page component as props
  };
};

const Home: NextPage<Props> = (props) => {
  console.log(new Date().getTimezoneOffset());

  return (
    <div className={styles.container}>
      <Head>
        <title>Next.js Clocks</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Clocks!</h1>

        <p className={styles.description}>
          Your IP is <code className={styles.code}>{props.ip}</code>
        </p>

        <p className={styles.description}>
          Your Time Zone is{" "}
          <code className={styles.code}>{props.timezone}</code>
        </p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>UTC Clock&rarr;</h2>
            <Clock timezone="UTC" offset={0} />
          </div>
          <div className={styles.card}>
            <h2>Clock 1&rarr;</h2>
            <Clock timezone={props.timezone} offset={props.offset} />
          </div>

          {/* <div className={styles.card}>
            <h2>Clock 1&rarr;</h2>
            <Suspense fallback={<div>Loading...</div>}>
              <Clock timezone={props.timezone} offset={props.offset}/>
            </Suspense>
          </div>

          <div className={styles.card}>
            <h2>Clock 1&rarr;</h2>
            <Suspense fallback={<div>Loading...</div>}>
              <Clock timezone={props.timezone} offset={props.offset}/>
            </Suspense>
          </div>

          <div className={styles.card}>
            <h2>Clock 1&rarr;</h2>
            <Suspense fallback={<div>Loading...</div>}>
              <Clock timezone={props.timezone} offset={props.offset}/>
            </Suspense>
          </div> */}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
